# Generated by Django 5.2.13 on 2026-04-08 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_reports", "Peut voir les rapports"),
                    ("can_manage_users", "Peut gérer les utilisateurs"),
                    ("can_validate_orders", "Peut valider les commandes"),
                    ("can_manage_inventory", "Peut gérer l'inventaire"),
                ]
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="contract_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, default="France", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direction", "Direction"),
                    ("administration", "Administration"),
                    ("comptabilite", "Comptabilité"),
                    ("rh", "Ressources Humaines"),
                    ("commercial", "Commercial"),
                    ("ventes", "Ventes"),
                    ("achats", "Achats"),
                    ("magasin", "Magasin"),
                    ("logistique", "Logistique"),
                    ("technique", "Technique"),
                    ("marketing", "Marketing"),
                    ("informatique", "Informatique"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Administrateur général"),
                    ("commercial", "Commercial"),
                ],
                default="commercial",
                max_length=20,
            ),
        ),
    ]
