# Generated by Django 5.2.13 on 2026-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
