# Generated by Django 5.2.13 on 2026-05-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="price_type",
            field=models.CharField(
                choices=[("retail", "Prix de détail"), ("wholesale", "Prix de gros")],
                default="retail",
                max_length=20,
                verbose_name="Type de prix",
            ),
        ),
    ]
