# Generated by Django 5.2.13 on 2026-05-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("sales", "0002_sale_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_items",
                to="inventory.warehouse",
            ),
        ),
    ]
